package wendy.practice;

import java.util.HashMap;
import java.util.Map;

public class ElementManager {
	private Map<String, String> elements = null;
	
	public ElementManager(){
		elements = new HashMap<String, String>();
		
		elements.put("H", "H");
		elements.put("He", "He");
		elements.put("Li", "Li");
		elements.put("Be", "Be");
		elements.put("B", "B");
		elements.put("C", "C");
		elements.put("N", "N");
		elements.put("O", "O");
		elements.put("F", "F");
		elements.put("Ne", "Ne");
		elements.put("Na", "Na");
		elements.put("Mg", "Mg");
		elements.put("Si", "Si");
		elements.put("P", "P");
		elements.put("S", "S");
		elements.put("Cl", "Cl");
		elements.put("Ar", "Ar");
		elements.put("Ca", "Ca");
		elements.put("Sc", "Sc");
		elements.put("Ti", "Ti");
		elements.put("V", "V");
		elements.put("Cr", "Cr");
		elements.put("Mn", "Mn");
		elements.put("Fe", "Fe");
		elements.put("Co", "Co");
		elements.put("Ni", "Ni");
		elements.put("Cu", "Cu");
		elements.put("Zn", "Zn");
		elements.put("Ga", "Ga");
		elements.put("Ge", "Ge");
		elements.put("As", "As");
		elements.put("Se", "Se");
		elements.put("Br", "Br");
		elements.put("Kr", "Kr");
		elements.put("Sr", "Sr");
		elements.put("Y", "Y");
		elements.put("Zr", "Zr");
		elements.put("Nb", "Nb");
		elements.put("Mo", "Mo");
		elements.put("Tc", "Tc");
		elements.put("Ru", "Ru");
		elements.put("Rh", "Rh");
		elements.put("Pd", "Pd");
		elements.put("Ag", "Ag");
		elements.put("Cd", "Cd");
		elements.put("In", "In");
		elements.put("Sn", "Sn");
		elements.put("Sb", "Sb");
		elements.put("Te", "Te");
		elements.put("I", "I");
		elements.put("Xe", "Xe");
		elements.put("Ba", "Ba");
		elements.put("Hf", "Hf");
		elements.put("Ta", "Ta");
		elements.put("W", "W");
		elements.put("Re", "Re");
		elements.put("Os", "Os");
		elements.put("Ir", "Ir");
		elements.put("Pt", "Pt");
		elements.put("Au", "Au");
		elements.put("Hg", "Hg");
		elements.put("Tl", "Tl");
		elements.put("Pb", "Pb");
		elements.put("Bi", "Bi");
		elements.put("Po", "Po");
		elements.put("At", "At");
		elements.put("Rn", "Rn");
		elements.put("Ra", "Ra");
		elements.put("Rf", "Rf");
		elements.put("Db", "Db");
		elements.put("Sg", "Sg");
		elements.put("Bh", "Bh");
		elements.put("Hs", "Hs");
		elements.put("Mt", "Mt");
		elements.put("Ds", "Ds");
		elements.put("Rg", "Rg");
		elements.put("Cn", "Cn");
		elements.put("Fl", "Fl");
		elements.put("Lv", "Lv");
		elements.put("La", "La");
		elements.put("Ce", "Ce");
		elements.put("Pr", "Pr");
		elements.put("Nd", "Nd");
		elements.put("Pm", "Pm");
		elements.put("Sm", "Sm");
		elements.put("Eu", "Eu");
		elements.put("Gd", "Gd");
		elements.put("Tb", "Tb");
		elements.put("Dy", "Dy");
		elements.put("Ho", "Ho");
		elements.put("Er", "Er");
		elements.put("Tm", "Tm");
		elements.put("Yb", "Yb");
		elements.put("Lu", "Lu");
		elements.put("Ac", "Ac");
		elements.put("Th", "Th");
		elements.put("Pa", "Pa");
		elements.put("U", "U");
		elements.put("Np", "Np");
		elements.put("Pu", "Pu");
		elements.put("Am", "Am");
		elements.put("Cm", "Cm");
		elements.put("Bk", "Bk");
		elements.put("Cf", "Cf");
		elements.put("Es", "Es");
		elements.put("Fm", "Fm");
		elements.put("Md", "Md");
		elements.put("No", "No");
		elements.put("Lr", "Lr");
	}
	
	public Map<String, String> getElement(){
		return elements;
	}
}
